POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba",
    "email": "rp@hm.com",
    "password":"123456"
}

### login sin conexion a BDD

POST  http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba2",
    "email":"rp2@hm.com",
    "password":"1234567"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGcioiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJl
